% Options for packages loaded elsewhere
\PassOptionsToPackage{unicode}{hyperref}
\PassOptionsToPackage{hyphens}{url}
%
\documentclass[
]{article}
\usepackage{amsmath,amssymb}
\usepackage{lmodern}
\usepackage{iftex}
\ifPDFTeX
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
\else % if luatex or xetex
  \usepackage{unicode-math}
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
\fi
% Use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{microtype.sty}{% use microtype if available
  \usepackage[]{microtype}
  \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\makeatletter
\@ifundefined{KOMAClassName}{% if non-KOMA class
  \IfFileExists{parskip.sty}{%
    \usepackage{parskip}
  }{% else
    \setlength{\parindent}{0pt}
    \setlength{\parskip}{6pt plus 2pt minus 1pt}}
}{% if KOMA class
  \KOMAoptions{parskip=half}}
\makeatother
\usepackage{xcolor}
\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\IfFileExists{bookmark.sty}{\usepackage{bookmark}}{\usepackage{hyperref}}
\hypersetup{
  pdftitle={Informe sobre la protección social y el trabajo en China},
  pdfauthor={Alexander Noblejas},
  hidelinks,
  pdfcreator={LaTeX via pandoc}}
\urlstyle{same} % disable monospaced font for URLs
\usepackage[margin=1in]{geometry}
\usepackage{graphicx}
\makeatletter
\def\maxwidth{\ifdim\Gin@nat@width>\linewidth\linewidth\else\Gin@nat@width\fi}
\def\maxheight{\ifdim\Gin@nat@height>\textheight\textheight\else\Gin@nat@height\fi}
\makeatother
% Scale images if necessary, so that they will not overflow the page
% margins by default, and it is still possible to overwrite the defaults
% using explicit options in \includegraphics[width, height, ...]{}
\setkeys{Gin}{width=\maxwidth,height=\maxheight,keepaspectratio}
% Set default figure placement to htbp
\makeatletter
\def\fps@figure{htbp}
\makeatother
\setlength{\emergencystretch}{3em} % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\setcounter{secnumdepth}{-\maxdimen} % remove section numbering
\ifLuaTeX
  \usepackage{selnolig}  % disable illegal ligatures
\fi

\title{Informe sobre la protección social y el trabajo en China}
\author{Alexander Noblejas}
\date{}

\begin{document}
\maketitle

\hypertarget{uxedndice}{%
\section{ÍNDICE}\label{uxedndice}}

\textbf{1. Introducción y objetivos} \textbf{2. Desarrollo del análisis}
\textbf{2.1 Promedio mundial de los indicadores en contraste con China}
\textbf{2.2 Relación entre el Índice de Desarrollo Humano (IDH) y el
porcentaje de empleadores por país} \textbf{2.3 Países según el nivel de
empleo vulnerable} \textbf{2.4 Densidad de la población económicamente
activa} \textbf{2.5 Frecuencia de los niveles de empleo vulnerable en el
mundo} \textbf{3. Conclusiones}

\hypertarget{uxedntroducciuxf3n-y-objetivos}{%
\section{1. ÍNTRODUCCIÓN Y
OBJETIVOS}\label{uxedntroducciuxf3n-y-objetivos}}

Actualmente ya no podemos desconocer el papel de nuestro país dentro del
escenario internacional. China, junto con Rusia, hemos sido catalogados
por la literatura occidental como una potencia revisionista, debido a
que nuestra irrupción en el sistema internacional ha representado una
amenaza para la posición hegemónica que por muchos años ha mantenido
Estados Unidos. Sin embargo, también es necesario poder centrarnos en
los procesos y fenómenos internos de nuestro estado, debido a que
necesitamos tener un panorama más completo del desarrollo de China. Es a
partir de ello que surge la necesidad de cuestionarnos sobre los avances
en la calidad de vida de los ciudadanos en China, especialmente en el
rubro laboral porque la industria de nuestro país a sido uno de nuestros
más asertados avances.

Este reporte está dirigido a Oficina de estudios económicos y
evaluaciones del Ministerio de Protección Social y el Trabajo para
iniciar con el programa de políticas públicas basado en evidencia que se
está impulsado desde el 2019. Este trabajo tiene como objetivo analizar
los avances de China en materia de protección social y trabajo. De
manera que podamos conocer si este rubro debo o no representar una de
las prioridades del estado Chino. Para acercanos al panorama laborar del
China, se ha seleccionado tres (03) indicadores: el porcentaje del
empleadores, el porcentaje de empleo vulnerable y la población activa
total. Estos se describen a continuación:

\begin{itemize}
\item
  \textbf{Empleadores, total (\% del empleo total)}: Empleadores se
  refiere a aquellos trabajadores que, por cuenta propia o con unos
  pocos asociados, mantienen el tipo de trabajo que se define como
  ``empleo por cuenta propia'', es decir: trabajos en los que la
  remuneración depende directamente de las utilidades derivadas de los
  bienes y servicios producidos, y que, en esta capacidad, han
  comprometido a una o más personas para trabajar con ellos como
  empleado(s) de manera continua. Fuente: Indicadores clave del mercado
  de trabajo ( KILM, por sus siglas en inglés ) de la OIT.
\item
  \textbf{Empleo vulnerable, total (\% del total de empleo)}: El empleo
  vulnerable se refiere a los trabajadores familiares no remunerados y a
  los trabajadores autónomos como porcentaje del empleo total.Fuente:
  Organización Internacional del Trabajo, base de datos de Indicadores
  principales sobre el mercado laboral.
\item
  \textbf{Población activa, total}: La población activa total comprende
  a personas de 15 años o más que satisfacen la definición de la
  Organización Internacional del Trabajo de población económicamente
  activa: todas las personas que aportan trabajo para la producción de
  bienes y servicios durante un período específico. Incluye tanto a las
  personas con empleo como a las personas desempleadas. Si bien las
  prácticas nacionales varían en el tratamiento de grupos como las
  fuerzas armadas o los trabajadores estacionales o a tiempo parcial, en
  general, la población activa incluye a las fuerzas armadas, a los
  desempleados, a los que buscan su primer trabajo, pero excluye a
  quienes se dedican al cuidado del hogar y a otros trabajadores y
  cuidadores no remunerados. Fuente: Organización Internacional del
  Trabajo, base de datos de Indicadores principales sobre el mercado
  laboral.
\end{itemize}

\hypertarget{desarrollo-del-anuxe1lisis}{%
\section{2. DESARROLLO DEL ANÁLISIS}\label{desarrollo-del-anuxe1lisis}}

\hypertarget{promedio-mundial-de-los-indicadores-en-contraste-con-china-tabla}{%
\subsection{2.1 Promedio mundial de los indicadores en contraste con
China
(Tabla)}\label{promedio-mundial-de-los-indicadores-en-contraste-con-china-tabla}}

Para empezar con el análisis de la protección social y el trabajo en
China, es importante conocer la ubicación de nuestro país en los
indicadores seleccionados. Para ello, se promedia los valores de todos
los estados de nuestra base de datos para luego contrastarlo con los
valores de China en población económicamente activa, procentaje de
empleadores y el índice de desarrollo humano.

\begin{verbatim}
##           PROMEDIO Promedio_Poblacionact Promedio_Empleadores Promedio_IDH
## 1 PROMEDIO MUNDIAL              21592922             3.360815    0.7330741
## 2            CHINA             800020955             2.110000    0.7610000
\end{verbatim}

Como se puede observar en la TABLA, en promedio existen 21 592 922
personas economicamente activas en un país y China está muy por encima
del promedio de población activa en el mundo. Asimismo, el promedio del
porcentaje de empleasdores a nivel mundial es de 3.36, donde China está
por debajo con 2.11. Para saber si esos resultados son indicadores
positivos para el desarrollo de nuestro estado, es importante compararlo
con el IDH. En promedio, el índice de desarrollo humano es de 0.73 en el
mundo, donde China tiene un valor de 0.76.

Es releante resaltar que el valor del IDH de China está ligeramente por
encima del promedio a nivel mundial. Sin embargo, en los siguientes
analisis de los resultados veremos si ello corresponde al avance en
temas de calidad del trabajo o si tenemos que extendernos a otros
estudios para tener esa informacipon.

\hypertarget{la-relaciuxf3n-del-idh-con-el-procentanje-de-empleadores-por-pauxeds}{%
\subsection{2.2 La relación del IDH con el procentanje de empleadores
por
país}\label{la-relaciuxf3n-del-idh-con-el-procentanje-de-empleadores-por-pauxeds}}

Si aplicamos una correlación entre estas dos variables tendremos el
siguiente resultado:

\begin{verbatim}
## [1] 0.3499156
\end{verbatim}

Esto quiere decir que existe una relación pequeña entre ambas variables
y que esta es positiva. Es decir, mientras más empleadores existen en un
país, mejor será el índice de desarrollo humano. Para ver si los datos
tiene ese comportamiento podemos mostrarun gráficos de dispersión de
puntos:

\includegraphics{REPORTE-FINAL--CHINA_files/figure-latex/unnamed-chunk-8-1.pdf}

El gráfico confirma que existe esa relación pequeña entre el IDH y el
procentaje de empleadores en cada páis. Asimismo, el gráfico nos da
otros alcances porque podemos observar que los países con un índice de
desarrollo humano muy alto -entre los más altos del mundo- como japón,
Noruega, Suiza, Luxemburgo, entre otros,se concentran en el lado derecho
inferior del gráfico y, contrarioa ello, los países africanos con menor
IDH se ubican en la parte inferior izquierdo de la tabla. Esto nos
indicaría que un mayor procentaje de empleadores en un país no
necesariamente conduce a la mejora de la calidad de vida de las
personas, sino que puede responder a la formalización y/o a otras formas
de ingresar al empleo como aquellas que proporcionan los Estados.

Asimismo, se observa en el punto rojo la posición de China.Si bien no
supera el 0.8 de IDH, se encuentra dentro del grupo de países como
México, Ecuador y Colombia. Es decir, que su idh y la cantidad de
procentaje de empleadores es similar a la de los países centro y
sudamericanos. Detrás aún de los países europeos y nórdicos. Se sigue
concluyendo en esta parte que la mejora en el bienestar de ciudadano no
necesariamente implica contar con más personas que den empleo Esto puede
responder a la calidad o tipo de trabajo que predomine o se de en un
país. Por ese motivo, para complejizar el análisis adicionaremos el
nivel de empleo vulnerable en los países.

\hypertarget{pauxedses-seguxfan-el-nivel-de-empleo-vulnerable}{%
\subsection{2.3 Países según el nivel de empleo
vulnerable}\label{pauxedses-seguxfan-el-nivel-de-empleo-vulnerable}}

Se elaboró una variable categórica ordinal para que nos indique la
categoría en la que podrían estar ubicados los países respecto a la
protección social y el trabajo. En este caso se usó el indicador del
``Empleo vulnerable'' para hacer una variable categórica ordinal. De
manera que nos indique por niveles qué paises tiene los porcetajes más
elevando de empleos vulnerables respecto al empleo total; es decir, qué
países tienen más o menos trabajadores familiares no remunerados y/o
trabajadores autónomos como porcentaje del empleo total.

Respecto a lo mencionado, los trabajos no remunerados o que corresponden
alguna vulnerabilidad económica para la persona tendría que tener
relación con el Índice del Desarrollo Humano. Así como vimos que los
países europeos y nórdicos se agruparon en el gráfico anterior, se
espera que se refleje lo mismo respecto al empleo vulnerable (\% del
total del empleo) y que nos permita comprender los niveles de desarrollo
de los países en función de la protección social y trabajo en cada uno
de ellos, especialmente en China que es nuestro caso de mayor interés.

\includegraphics{REPORTE-FINAL--CHINA_files/figure-latex/unnamed-chunk-16-1.pdf}

Como se puede observar en el MAPA DEL MUNDO, durante el 2019 los países
europeos son los que tienen niveles más bajos en procentaje de empleo
vulnerable. De acuerdo con los datos, el empleo vulnerable en estos
países se ubica entre ``casi inesxistente'', ``muy bajo'' o ``bajo''; es
decir, el empleo vulnerable no superar 31.5\% del total en esos países.
En contraste, en el continente africano apreciamos que allí se ubican
los países con mayor porcentaje de empleo vulnerable, incluso en niveles
de ``extremo'' que supera el 90\% del total. Aunque es importante
resaltar el caso atípico de Sudráfica que tiene un nivel de empleo
vulnerable ``muy bajo'' (entre 10.6\% y 21.1 \%).

En cuanto a China, se observa que, al igual que varios países del
continente asiático, se ubican en el nivel medio; es decir, los niveles
de empleo vulnerable en China se encuentran entre el 42\% y 52.5\% del
total. Asimismo, se evidencia que se trata de una característica más o
menos recurrente en la región asiática oriental con tendencia reducir
esos niveles.

Bajo el panorama mundial, el avance de China -potencia mundial- en temas
de protección social y trabajo se encuentra a niveles similares que
países en vías de desarrollo del continente Sudaméricano en casos como
Perú, Ecuador y Colombia. Aunque también hay casos con mejores niveles
que China, tales como Chile, Argentina, Uruguay y Brasil.

\hypertarget{densidad-de-la-poblaciuxf3n-econuxf3micamente-activa}{%
\subsection{2.4 Densidad de la población económicamente
activa}\label{densidad-de-la-poblaciuxf3n-econuxf3micamente-activa}}

\begin{itemize}
\tightlist
\item
  Estadísticos descriptivos de la variable ``Población activa'':
\end{itemize}

\begin{verbatim}
##      Min.   1st Qu.    Median      Mean   3rd Qu.      Max. 
##     31687   1439472   4238924  21592922  13137960 800020955
\end{verbatim}

Los estadísticos descriptivos nos indican que a nivel mundial existe una
gran diferencia en la cantidad de población activa entre los países. Por
un lado, se identifica a China como el país que más población
económicamente activa tiene con un total de 800 020 955 personas. Por
otro lado, se reconoce a Tonga como el país que menos población activa
posee con un total de 31 687 personas.

Asimismo, vemos que en promedio existen 21 592 922 personas
economicamente activas entre los países del mundo. Lo que nos indica la
importancia de seguir analizando este factor dentro de los países. Lo
mencionado podemos verlo en un gráfico de densidad:

\includegraphics{REPORTE-FINAL--CHINA_files/figure-latex/unnamed-chunk-18-1.pdf}

El grafico de densidad también nos muestra la enorme diferencia en
cuanto al número de población económicamente activa en el mundo. Hay
mucha más concetración de países cuyo número de población economicamente
activa es menor a la del promedio mundial (21 592 922 personas), tal
como indica la línea vertical. Más bien, existen una gran diferencia en
cuanto a aquellos países como China, India y Estados Unidos (los tres
países más importantes en la economía mundial) con una inmensa cantidad
de población activa que superan los 160 millones de personas y aquellos
que tienen muy poca como Tonga, Samo y San Vicente que no superan los 60
mil.

\hypertarget{frecuencia-de-los-niveles-de-empleo-vulnerable-en-el-mundo}{%
\subsection{2.5 Frecuencia de los niveles de empleo vulnerable en el
mundo}\label{frecuencia-de-los-niveles-de-empleo-vulnerable-en-el-mundo}}

Es importante para este reporte contrastar la ubicación de China
respecto a los niveles de empleo vulnerable, debido a que este indicador
no se pudo incluir en el cuadro de promedios por ser una variable
categórica ordinal. Primero observanos la distribución de manera
numérica:

\begin{verbatim}
## 
## Casi inexistente         Muy bajo             Bajo       Medio-bajo 
##               28               21               23               14 
##            Medio       Medio-alto             Alto         Muy alto 
##               15                6                7               12 
##          Extremo 
##                9
\end{verbatim}

Ahora creamos una gráfico de barras sobre la frecuencia de la variable
en mención:
\includegraphics{REPORTE-FINAL--CHINA_files/figure-latex/unnamed-chunk-20-1.pdf}

Como se ha mencionado anteriormente, China está ubicada en el nivel
medio; es decir, el procentaje del empleo vunerable en nuestro país se
encuentran entre el 42\% y 52.5\% del total. El gráfico de barras nos
muestra que gran parte de los países en el mundo tienen un panorana
superior (mejor calidad del trabajo) a China respecto al procentaje de
empleo vulnerable. Muy por debajo de sus rivales económicos y políticos
como Estados Unidos que se ubica en el nivel de ``casi inexistente'' (04
niveles menos).

Asimismo, la distribución de los países en el gráfico indica que la
mayor parte de los estados han avanzado respecto a la calidad de sus
trabajos, dejando a China en un panorama intermedio. Esto no debería ser
de esta manera si China quiere verse como un modelo a seguir y de gran
influencia para la región asiática y le mundo.

\hypertarget{conclusiones}{%
\section{Conclusiones}\label{conclusiones}}

En este informe concluímos con los siguientes puntos:

\begin{itemize}
\item
  China tiene un índice desarrollo humano ligeramente superior al
  promedio de los países en el mundo. Sin embargo, no podemos afirmar
  que esos indicadores positivos sobre nuestro país correspondan al
  ámbito de protección social y trabajo, debido a que se han evidenciado
  signos de limitaciones en comparación con otras potencias como Estados
  Unidos y la Unión Europea.
\item
  China ha mostrado tener la población económicamente activa más grande
  a nivel mundial; es decir, cuenta con un gran mercado laboral que
  puede usar a favor del desarrollo del país. Sin embargo, aún tiene que
  centrarce en hacer que estos trabajos sean de calidad, debido a que se
  ubica en un plano intermedio de empleo vulnerables a nivel mundial.
  Eso es significativo porque países en vias de desarrollo como Chile,
  Uruguay y Brasil superan a China en este ámbito. EE.UU., al igual que
  otros 25 páises más, superan a China hasta en 4 niveles de 9.
\item
  Al encontrarse que un mayor número de empleadores no necesariamente
  explica o está relacioanda a mejores índices de desarrollo humano,
  China debe centrarse en garantizar un trabajo en mejores condiciones
  para sus ciudadanos. Para ello puede adoptar medidas como la
  formalizarción.
\item
  Finalmente, el panorama de China en el sector laboral es similar a la
  del resto de los países en el Asia Oriental, por lo que debe liderar
  en este rubro para seguir posicionandose como potencia en el resto de
  los países. Nuestro país no ha mostrado ser un país laboralmente
  amigable para sus ciudadanos y está en tiempo de hacerlo.
\end{itemize}

\end{document}
